"""The shared ACEUIModLoader test kit (modkit.py in the loader repo) plus this mod's own contract."""
import json
import os
import re
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOADER = os.environ.get("ACE_LOADER_DIR") or os.path.join(os.path.dirname(ROOT), "ACEUIModLoader")
sys.path.insert(0, os.path.join(LOADER, "tools"))

from modkit import ModTests  # noqa: E402

MOD = os.path.join(ROOT, "doom")
JS = os.path.join(MOD, "doom.js")
WASM = os.path.join(ROOT, "third_party", "doom.wasm")
MODULE = os.path.join(MOD, "doomjs.js")


class Tests(ModTests):
    ROOT = ROOT
    MIN_CASES = 11
    HOT_PATH = ("// ---- rendering", "// ---- state changes")


def read_leb(data, pos):
    result = shift = 0
    while True:
        byte = data[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        shift += 7
        if not byte & 0x80:
            return result, pos


def read_name(data, pos):
    length, pos = read_leb(data, pos)
    return data[pos:pos + length].decode(), pos + length


def wasm_imports(path):
    """(module, name) of every function import in the binary's import section."""
    with open(path, "rb") as f:
        data = f.read()
    assert data[:4] == b"\0asm", "not a WebAssembly binary"
    pos, found = 8, []
    while pos < len(data):
        section_id = data[pos]
        size, pos = read_leb(data, pos + 1)
        if section_id == 2:
            count, p = read_leb(data, pos)
            for _ in range(count):
                module, p = read_name(data, p)
                name, p = read_name(data, p)
                kind = data[p]
                p += 1
                _, p = read_leb(data, p)
                if kind == 0:
                    found.append((module, name))
            break
        pos += size
    return found


class DoomContractTests(unittest.TestCase):
    """What the host promises beyond the kit's rules."""

    def setUp(self):
        with open(JS, encoding="utf-8") as f:
            self.js = f.read()

    def test_the_module_ships_and_every_import_it_needs_is_provided(self):
        with open(os.path.join(MOD, "mod.json"), encoding="utf-8") as f:
            info = json.load(f)
        self.assertEqual(info["files"], ["doomjs.js"], "the JavaScript build ships; the game exposes no WebAssembly")
        self.assertEqual(info["scripts"], ["png.js", "saves.js", "audiomap.js", "doom.js"], "the encoder, save codec and audio map load before the host")
        self.assertGreater(os.path.getsize(WASM), 4_000_000, "the shareware WAD is embedded")
        imports = wasm_imports(WASM)
        self.assertEqual(len(imports), 13, "upstream's ten plus ACEDOOM's three audio hooks (tools/build_wasm.py)")
        self.assertEqual(sorted(name for module, name in imports if module == "audio"), ["onMusicStart", "onMusicStop", "onSoundStart"])
        block = self.js[self.js.find("const imports = function"):self.js.find("/** keyCode -> DOOM key code")]
        for module, name in imports:
            self.assertRegex(block, rf"\b{module}: \{{", f"import module {module}")
            self.assertRegex(block, rf"\b{name}: function", f"import {module}.{name}")
        self.assertIn("getTempRet0: function", block, "wasm2js legalises the i64 clock through env.getTempRet0")
        with open(MODULE, encoding="utf-8") as f:
            head = f.read(2000)
            f.seek(0)
            body = f.read()
        self.assertIn("GENERATED by tools/build_module.py", head)
        self.assertIn("var ACEDoomModule = (function () {", head)
        self.assertIn("function asmFunc(imports) {", body)
        self.assertIsNone(re.search(r"^(import|export) ", body, re.M), "classic script, not an ES module")
        self.assertTrue(body.rstrip().endswith("return asmFunc;\n}());"), "the factory is the global")
        self.assertNotIn("WebAssembly.", self.js, "the host never touches WebAssembly")

    def test_saving_is_implemented_rather_than_stubbed_out(self):
        """doom.wasm leaves saving to its host; returning 0 from these is what "no saving" looks like."""
        block = self.js[self.js.find("gameSaving: {"):self.js.find("loading: {")]
        self.assertNotIn("return 0; }", block, "the three gameSaving imports must do real work")
        for call in ("sizeOfSave(state, slot)", "readSave(state, slot, ptr)", "writeSave(state, slot, ptr, length)"):
            self.assertIn(call, block, f"gameSaving wired to {call}")
        self.assertIn("return length;", self.js, "the module compares what we return with the length it passed")
        self.assertIn("ACEDoomSaves.encode", self.js, "slots are compacted before they are stored")
        self.assertIn("ACEDoomSaves.decode", self.js)
        self.assertIn("persist.writeStore(SAVES_KEY", self.js, "and reach disk through the engine container")

    def test_the_pixel_path_is_blob_urls_never_data_urls(self):
        self.assertIn("URL.createObjectURL(new Blob(", self.js)
        self.assertIn("URL.revokeObjectURL(", self.js)
        self.assertNotIn("data:image", self.js, "data: URLs are capped at 2048 characters in the game's Cohtml")
        self.assertNotIn("putImageData", self.js, "no ImageData in the game's Cohtml")

    def test_escape_is_never_taken_from_the_game(self):
        self.assertIn('const TOGGLE_KEY = "Insert";', self.js)
        self.assertIn('const MENU_KEY = "Delete";', self.js)
        self.assertIn('[MENU_KEY, "KEY_ESCAPE"]', self.js, "Delete stands in for DOOM's Escape")
        self.assertNotIn('["Escape"', self.js)
        self.assertNotIn("Escape: 27", self.js, "the real Escape pauses the sim and reloads the HUD; it must pass through")

    def test_the_clock_is_legalised_and_only_runs_while_open(self):
        clock = self.js[self.js.find("timeInMilliseconds: function"):self.js.find("ui: {")]
        self.assertIn("return Math.floor(doom.clockMs);", clock, "low 32 bits of the legalised i64 import")
        self.assertIn("if (doom.polls > POLL_LIMIT) {", clock, "busy-waits inside one tick must end")
        self.assertIn("state.doom.polls = 0;", self.js)
        self.assertIn("if (!state.open || ACEUIModLoader.hudHidden() || doom.phase !== PHASE.running) {", self.js)
        self.assertIn("doom.clockMs += step;", self.js)
        self.assertIsNone(re.search(r"setInterval|setTimeout", self.js), "the shared frame loop drives the game")


class BankPatchTests(unittest.TestCase):
    """tools/patch_bank.py: the rebuilt gui.bank must be what FMOD expects (launches 29-32 taught each rule)."""

    @classmethod
    def setUpClass(cls):
        sys.path.insert(0, os.path.join(ROOT, "tools"))
        import patch_bank
        cls.pb = patch_bank
        try:
            cls.stock = patch_bank.stock_gui_bank()
        except SystemExit:
            raise unittest.SkipTest("needs the installed game (content.kspkg)")

    def test_rebuild_without_changes_is_byte_identical(self):
        out, report = self.pb.patch(self.stock, b"", {})
        self.assertEqual(out, self.stock)
        self.assertEqual(report, [])

    def test_swapping_a_sample_keeps_every_other_sample_and_fixes_every_size(self):
        import struct
        out, report = self.pb.patch(self.stock, self.stock, {"click.6": "stock:confirm"})
        self.assertEqual(len(report), 1)
        snd, fsb = self.pb.split_bank(out)
        fields, samples = self.pb.parse_fsb5(out[fsb:])
        _, stock_samples = self.pb.parse_fsb5(self.stock[self.stock.find(b"FSB5"):])
        names = [s.name for s in stock_samples]
        self.assertEqual([s.name for s in samples], names, "names and order unchanged")
        self.assertEqual(samples[names.index("click.6")].data, stock_samples[names.index("confirm")].data)
        for k, s in enumerate(samples):
            if names[k] != "click.6":
                self.assertEqual(s.data, stock_samples[k].data, names[k])
        self.assertEqual(struct.unpack_from("<I", out, 4)[0], len(out) - 8, "RIFF size")
        self.assertEqual(struct.unpack_from("<I", out, snd + 4)[0], len(out) - (snd + 8), "SND chunk size")
        sndh = out.rfind(b"SNDH", 0, snd)
        self.assertEqual(struct.unpack_from("<III", out, sndh + 8)[1:], (fsb, len(out) - fsb), "SNDH offset and size")
        headers, names_size = struct.unpack_from("<II", out, fsb + 12)
        self.assertEqual((fsb + 60 + headers + names_size) % 32, 0, "sample data 32-byte aligned")

    def test_refuses_a_bank_in_another_sample_format(self):
        pcm = bytearray(self.stock)
        fsb = pcm.find(b"FSB5")
        pcm[fsb + 24:fsb + 28] = (2).to_bytes(4, "little")     # pretend PCM16
        with self.assertRaises(SystemExit):
            self.pb.patch(self.stock, bytes(pcm), {"click.6": "confirm"})


if __name__ == "__main__":
    unittest.main()
