/*
 * audiomap.js -- GENERATED by tools/build_audio.py from audio/sounds.json, do not edit.
 *
 * Which of the game's GUI event types plays which DOOM sound: the host asks the game
 * for the type (UIAudioRequestAudioEvent) and the stock event plays the sample that
 * tools/patch_bank.py swapped for DOOM's inside gui.bank. Numbers are DOOM's own
 * S_sfx / S_music indices, reported by the module's audio imports.
 */
const ACEDoomAudioMap = (function () {
    return {
        sfx: {
            1: "GUI_MONEY_GAIN",
            2: "GUI_MONEY_GAIN",
            4: "GUI_MONEY_GAIN",
            15: "GUI_SWITCH_ON",
            18: "GUI_SWITCH_OFF",
            19: "GUI_SWITCH_OFF",
            20: "GUI_SWITCH_OFF",
            21: "GUI_SWITCH_OFF",
            22: "GUI_SWITCH_OFF",
            23: "GUI_SWITCH_OFF",
            24: "GUI_SWITCH_OFF",
            25: "GUI_MONEY_LOSS",
            26: "GUI_MONEY_LOSS",
            27: "GUI_MONEY_LOSS",
            34: "GUI_MONEY_LOSS",
            57: "GUI_MONEY_LOSS",
            58: "GUI_MONEY_LOSS",
            59: "GUI_MONEY_LOSS",
            60: "GUI_MONEY_LOSS",
            61: "GUI_MONEY_LOSS",
            62: "GUI_MONEY_LOSS",
            63: "GUI_MONEY_LOSS",
            64: "GUI_MONEY_LOSS",
            82: "GUI_SWITCH_ON",
            86: "GUI_MONEY_GAIN",
            88: "GUI_SWITCH_OFF",
            89: "GUI_SWITCH_OFF"
        },
        music: {
            1: { gui: "GUI_PART_APPLY", seconds: 103 },
            2: { gui: "GUI_PART_APPLY", seconds: 103 },
            3: { gui: "GUI_PART_APPLY", seconds: 103 },
            4: { gui: "GUI_PART_APPLY", seconds: 103 },
            5: { gui: "GUI_PART_APPLY", seconds: 103 },
            6: { gui: "GUI_PART_APPLY", seconds: 103 },
            7: { gui: "GUI_PART_APPLY", seconds: 103 },
            8: { gui: "GUI_PART_APPLY", seconds: 103 },
            9: { gui: "GUI_PART_APPLY", seconds: 103 }
        },
        names: ["none", "pistol", "shotgn", "sgcock", "dshtgn", "dbopn", "dbcls", "dbload", "plasma", "bfg", "sawup", "sawidl", "sawful", "sawhit", "rlaunc", "rxplod", "firsht", "firxpl", "pstart", "pstop", "doropn", "dorcls", "stnmov", "swtchn", "swtchx", "plpain", "dmpain", "popain", "vipain", "mnpain", "pepain", "slop", "itemup", "wpnup", "oof", "telept", "posit1", "posit2", "posit3", "bgsit1", "bgsit2", "sgtsit", "cacsit", "brssit", "cybsit", "spisit", "bspsit", "kntsit", "vilsit", "mansit", "pesit", "sklatk", "sgtatk", "skepch", "vilatk", "claw", "skeswg", "pldeth", "pdiehi", "podth1", "podth2", "podth3", "bgdth1", "bgdth2", "sgtdth", "cacdth", "skldth", "brsdth", "cybdth", "spidth", "bspdth", "vildth", "kntdth", "pedth", "skedth", "posact", "bgact", "dmact", "bspact", "bspwlk", "vilact", "noway", "barexp", "punch", "hoof", "metal", "chgun", "tink", "bdopn", "bdcls", "itmbk", "flame", "flamst", "getpow", "bospit", "boscub", "bossit", "bospn", "bosdth", "manatk", "mandth", "sssit", "ssdth", "keenpn", "keendt", "skeact", "skesit", "skeatk", "radio"]
    };
}());
