/*
 * ACEDOOM -- FMOD Studio 2.03 script, GENERATED by tools/build_audio.py from audio/sounds.json
 * into audio/fmod/project/Scripts/acedoom.js (do not edit; edit the template in audio/fmod/).
 *
 * The project is Kunos's audio modding template (SDK, fmod_evo_020313_modding) with the car
 * sample assets left out. Their pipeline for a modded car: clone master_bank_template into a
 * new master bank, delete the template, add your events, build. Two menu items do that here:
 *
 *   ACEDOOM > 1. Prepare project     clone the master bank, mark it master, drop the template
 *                                    bank and the eight *_template car events (mixer untouched)
 *   ACEDOOM > 2. Add sounds and build import the DOOM WAVs and the music, one event each under
 *                                    event:/doom/, assigned to the master bank, then build
 *
 * The build lands in <project>/Build/sfx/ (platform "Desktop", sub-directory "sfx") as
 * master_bank.bank + master_bank.strings.bank; tools/install_bank.py copies them into
 * Saved Games\ACE\mods\content\sfx\acedoom\. Kunos's warning applies: never touch the mixer page.
 */
(function () {
    var SLOTS = /*SLOTS*/[];
    var MASTER_NAME = "master_bank";
    var TEMPLATE_NAME = "master_bank_template";
    var FOLDER_NAME = "doom";

    function log(text) { console.log("[ACEDOOM] " + text); }

    function banks() { return studio.project.model.Bank.findInstances(); }

    function bankNamed(name) {
        var all = banks();
        for (var i = 0; i < all.length; i++) { if (all[i].name === name) { return all[i]; } }
        return null;
    }

    function eventPath(event) {
        try { return event.getPath(); } catch (e) { return "event:/" + event.name; }
    }

    function eventAt(path) {
        var all = studio.project.model.Event.findInstances();
        for (var i = 0; i < all.length; i++) { if (eventPath(all[i]) === path) { return all[i]; } }
        return null;
    }

    function folderNamed(name) {
        var all = studio.project.model.EventFolder.findInstances();
        for (var i = 0; i < all.length; i++) { if (all[i].name === name) { return all[i]; } }
        var folder = studio.project.create("EventFolder");
        folder.name = name;
        folder.folder = studio.project.workspace.masterEventFolder;
        return folder;
    }

    function projectDir() {
        return studio.project.filePath.replace(/[\\\/][^\\\/]*$/, "");
    }

    studio.menu.addMenuItem({
        name: "ACEDOOM\\1. Prepare project",
        execute: function () {
            var template = bankNamed(TEMPLATE_NAME);
            var master = bankNamed(MASTER_NAME);
            var report = [];

            if (!master) {
                master = studio.project.create("Bank");
                master.name = MASTER_NAME;
                if (template) { try { master.folder = template.folder; } catch (e) {} }
                report.push("created bank " + MASTER_NAME);
            }
            try { master.isMasterBank = true; report.push(MASTER_NAME + " is the master bank"); }
            catch (e) { report.push("could not mark master by script: right-click " + MASTER_NAME + " > Mark as Master Bank: " + e); }

            var events = studio.project.model.Event.findInstances();
            var removed = 0;
            for (var i = events.length - 1; i >= 0; i--) {
                if (/_template\s*$/i.test(events[i].name || "")) {
                    try { studio.project.deleteObject(events[i]); removed++; } catch (e) { report.push("could not delete " + events[i].name + ": " + e); }
                }
            }
            report.push("removed " + removed + " *_template car events");

            if (template) {
                try { studio.project.deleteObject(template); report.push("deleted " + TEMPLATE_NAME); }
                catch (e) { report.push("delete " + TEMPLATE_NAME + " by hand: " + e); }
            }
            studio.project.save();
            for (var r = 0; r < report.length; r++) { log(report[r]); }
            alert(report.join("\n"));
        }
    });

    studio.menu.addMenuItem({
        name: "ACEDOOM\\2. Add sounds and build",
        execute: function () {
            var master = bankNamed(MASTER_NAME);
            var report = [];

            if (!master) { alert("run '1. Prepare project' first"); return; }

            var folder = folderNamed(FOLDER_NAME);

            for (var i = 0; i < SLOTS.length; i++) {
                var slot = SLOTS[i];
                var path = "event:/" + slot.event;

                if (eventAt(path)) { report.push("kept " + path); continue; }

                var asset = null;
                try { asset = studio.project.importAudioFile(slot.file); } catch (e) { report.push("import failed " + slot.file + ": " + e); continue; }
                if (!asset) { report.push("MISSING " + slot.file); continue; }
                if (slot.music) { try { asset.isStreaming = true; } catch (e) {} }

                var event = studio.project.create("Event");
                event.name = slot.name;
                event.folder = folder;

                var track = event.addGroupTrack();
                var length = 1;
                try { length = asset.length || 1; } catch (e) {}
                var sound = track.addSound(event.timeline, "SingleSound", 0, length);
                sound.audioFile = asset;

                event.relationships.banks.add(master);
                report.push("created " + path + " (" + Math.round(length * 100) / 100 + " s)");
            }

            studio.project.save();
            for (var r = 0; r < report.length; r++) { log(report[r]); }
            studio.project.build();
            alert(report.join("\n") + "\n\nBuilding. When it finishes, run in a terminal:\n  python tools/install_bank.py\n(from the ACEDOOM repo; it copies Build/sfx/master_bank*.bank into Saved Games\\ACE\\mods\\content\\sfx\\acedoom\\)");
        }
    });

    log("scripts loaded for project " + projectDir() + " with " + SLOTS.length + " DOOM slots");
}());
