"""
build_audio.py - everything the audio path derives from audio/sounds.json.

  1. doom/audiomap.js                the host's map: DOOM sound number -> GUI event type
                                     (classic script loaded before doom.js);
  2. audio/fmod/project/Scripts/acedoom.js
                                     the FMOD Studio menu script that imports every sfx the
                                     slots name and builds our bank (Vorbis, see README);
  3. build/package/content/sfx/gui.bank
                                     the game's UI bank with the slots' stock samples replaced by
                                     ours (tools/patch_bank.py), from the bank Studio built;
  4. with --pack / --install         ACEUIModLoaderMods-doom.kspkg carrying that gui.bank, packed by
                                     the loader's pack_kspkg.py (named to list after the loader).

Usage:
    python tools/build_audio.py [--pack] [--install] [--no-bank]

--no-bank skips step 3 (before Studio has built our bank). Steps 1 and 2 never need
the bank.
"""
import glob
import json
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import patch_bank  # noqa: E402

SOUNDS = os.path.join(ROOT, "audio", "sounds.json")
AUDIOMAP = os.path.join(ROOT, "doom", "audiomap.js")
STUDIO_TEMPLATE = os.path.join(ROOT, "audio", "fmod", "studio_template.js")
PROJECT = os.path.join(ROOT, "audio", "fmod", "project")
STUDIO_SCRIPT = os.path.join(PROJECT, "Scripts", "acedoom.js")
OUR_BANK_DIRS = (os.path.join(ROOT, "audio", "acevo_content"), os.path.join(PROJECT, "Build"))
MUSIC_DIR = os.path.join(os.path.dirname(ROOT), "console-doom", "music")
PACKAGE_DIR = os.path.join(ROOT, "build", "package")
PATCHED_BANK = os.path.join(PACKAGE_DIR, "content", "sfx", "gui.bank")
PACKAGE_NAME = "ACEUIModLoaderMods-doom.kspkg"
LOADER_TOOLS = os.path.join(os.environ.get("ACE_LOADER_DIR") or os.path.join(os.path.dirname(ROOT), "ACEUIModLoader"), "tools")

# S_sfx order in doomgeneric/src/sounds.c (index = the number I_StartSound reports)
SFX_NAMES = ("none pistol shotgn sgcock dshtgn dbopn dbcls dbload plasma bfg sawup sawidl sawful sawhit rlaunc rxplod "
             "firsht firxpl pstart pstop doropn dorcls stnmov swtchn swtchx plpain dmpain popain vipain mnpain pepain "
             "slop itemup wpnup oof telept posit1 posit2 posit3 bgsit1 bgsit2 sgtsit cacsit brssit cybsit spisit bspsit "
             "kntsit vilsit mansit pesit sklatk sgtatk skepch vilatk claw skeswg pldeth pdiehi podth1 podth2 podth3 "
             "bgdth1 bgdth2 sgtdth cacdth skldth brsdth cybdth spidth bspdth vildth kntdth pedth skedth posact bgact "
             "dmact bspact bspwlk vilact noway barexp punch hoof metal chgun tink bdopn bdcls itmbk flame flamst getpow "
             "bospit boscub bossit bospn bosdth manatk mandth sssit ssdth keenpn keendt skeact skesit skeatk radio").split()
# S_music order in sounds.c (index = the number S_ChangeMusic reports)
MUSIC_NAMES = ("none e1m1 e1m2 e1m3 e1m4 e1m5 e1m6 e1m7 e1m8 e1m9 e2m1 e2m2 e2m3 e2m4 e2m5 e2m6 e2m7 e2m8 e2m9 e3m1 e3m2 "
               "e3m3 e3m4 e3m5 e3m6 e3m7 e3m8 e3m9 inter intro bunny victor introa runnin stalks countd betwee doom the_da "
               "shawn ddtblu in_cit dead stlks2").split()

HEADER = """/*
 * audiomap.js -- GENERATED by tools/build_audio.py from audio/sounds.json, do not edit.
 *
 * Which of the game's GUI event types plays which DOOM sound: the host asks the game
 * for the type (UIAudioRequestAudioEvent) and the stock event plays the sample that
 * tools/patch_bank.py swapped for DOOM's inside gui.bank. Numbers are DOOM's own
 * S_sfx / S_music indices, reported by the module's audio imports.
 */
const ACEDoomAudioMap = (function () {
    return {
        sfx: {
%s
        },
        music: {
%s
        },
        names: [%s]
    };
}());
"""


def load():
    with open(SOUNDS, encoding="utf-8") as f:
        return json.load(f)


def write_audiomap(config):
    """One line per DOOM sound number: the slot's own sfx and every sound listed under `also`."""
    pairs = []
    for s in config["slots"]:
        if not s.get("gui"):
            continue
        for name in [s["sfx"]] + list(s.get("also", [])):
            if name not in SFX_NAMES:
                raise SystemExit(f"unknown sfx {name}")
            pairs.append((SFX_NAMES.index(name), s["gui"], name))
    pairs.sort()
    sfx = [f'            {index}: "{gui}"' for index, gui, name in pairs]
    music = [f'            {MUSIC_NAMES.index(m["music"])}: {{ gui: "{m["gui"]}", seconds: {m.get("seconds", 0)} }}'
             for m in config.get("music", []) if m.get("gui")]
    with open(AUDIOMAP, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER % (",\n".join(sfx), ",\n".join(music), ", ".join(f'"{n}"' for n in SFX_NAMES)))
    return len(sfx), len(music)


def write_studio_script(config):
    """The FMOD Studio menu script with the import list baked in (Studio scripts cannot read files)."""
    entries = []
    for slot in config["slots"]:
        if not slot.get("sfx"):
            continue
        file = os.path.join(ROOT, "audio", "sfx", slot["sfx"] + ".wav")
        entries.append({"name": slot["sfx"], "event": "doom/" + slot["sfx"], "file": file.replace("\\", "/"), "music": False})
    for track in config.get("music", []):
        file = os.path.join(MUSIC_DIR, "d_" + track["music"] + ".ogg")
        entries.append({"name": "music_" + track["music"], "event": "doom/music_" + track["music"],
                        "file": file.replace("\\", "/"), "music": True})
    with open(STUDIO_TEMPLATE, encoding="utf-8") as f:
        text = f.read()
    text = text.replace("/*SLOTS*/[]", json.dumps(entries, indent=8).replace("\n", "\n    "))
    os.makedirs(os.path.dirname(STUDIO_SCRIPT), exist_ok=True)
    with open(STUDIO_SCRIPT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return [e["file"] for e in entries if not os.path.isfile(e["file"])]


def our_bank():
    hits = [h for d in OUR_BANK_DIRS for h in glob.glob(os.path.join(d, "**", "master_bank.bank"), recursive=True)]
    if not hits:
        raise SystemExit("our bank not found: build the FMOD project (ACEDOOM > 2. Add sounds and build) first, or pass --no-bank")
    return max(hits, key=os.path.getmtime)


def write_patched_bank(config):
    mapping = {s["stockSample"]: (s["sfx"] if s.get("sfx") else "stock:" + s["copyStock"]) for s in config["slots"] if s.get("stockSample")}
    path = our_bank()
    with open(path, "rb") as f:
        ours = f.read()
    out, report = patch_bank.patch(patch_bank.stock_gui_bank(), ours, mapping)
    if os.path.isdir(PACKAGE_DIR):
        shutil.rmtree(PACKAGE_DIR)                 # the package holds exactly this one file
    os.makedirs(os.path.dirname(PATCHED_BANK), exist_ok=True)
    with open(PATCHED_BANK, "wb") as f:
        f.write(out)
    return path, len(out), report


def main(argv):
    config = load()
    for s in config["slots"]:
        if s.get("sfx") and s["sfx"] not in SFX_NAMES:
            raise SystemExit(f"unknown sfx {s['sfx']}")
    n_sfx, n_music = write_audiomap(config)
    print(f"wrote {AUDIOMAP}: {n_sfx} effects, {n_music} music slot(s)")
    missing = write_studio_script(config)
    print(f"wrote {STUDIO_SCRIPT}" + (f" (source files missing: {missing})" if missing else ""))
    if "--no-bank" not in argv:
        source, size, report = write_patched_bank(config)
        print(f"wrote {PATCHED_BANK} ({size:,} bytes) from {source}, {len(report)} sample(s) replaced:")
        print("\n".join(report))
    if "--pack" in argv or "--install" in argv:
        if not os.path.isfile(PATCHED_BANK):
            raise SystemExit("nothing to pack: build the bank first")
        out = os.path.join(ROOT, "dist", PACKAGE_NAME)
        cmd = [sys.executable, os.path.join(LOADER_TOOLS, "pack_kspkg.py"), PACKAGE_DIR, out]
        if "--install" in argv:
            cmd.append("--install")
        subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main(sys.argv[1:])
