"""
build_module.py - turn third_party/doom.wasm into doom/doomjs.js.

The game's Cohtml starts V8 with --noexpose_wasm (confirmed in game 2026-09-14:
`typeof WebAssembly` is "undefined" on every page), so the module cannot run as
WebAssembly there. binaryen's wasm2js translates it to plain JavaScript, which
V8 JIT-compiles like any other script. This tool runs wasm2js and rewrites its
ES-module output into a classic script that defines one global:

    ACEDoomModule(imports) -> the module's exports
                              (memory with a .buffer getter, initGame, tickGame,
                              reportKeyDown, reportKeyUp, KEY_* {value} objects)

`imports` is the wasm import object plus `env.getTempRet0`: wasm2js legalises
the i64-returning clock import into "low 32 bits returned, high 32 bits read
back through env.getTempRet0()".

Usage:
    python tools/build_module.py [--wasm2js <path to wasm2js.exe>]

wasm2js comes with binaryen: https://github.com/WebAssembly/binaryen/releases
(binaryen-version_123-x86_64-windows.tar.gz was used). Set WASM2JS or pass
--wasm2js when it is not on PATH. The output is committed, so players and the
tests never need binaryen.
"""
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "third_party", "doom.wasm")
OUTPUT = os.path.join(ROOT, "doom", "doomjs.js")
GLOBAL = "ACEDoomModule"
HEADER = """/*
 * doomjs.js -- GENERATED by tools/build_module.py, do not edit.
 *
 * jacobenget/doom.wasm v0.1.0 (id Software DOOM, GPL-2.0, shareware WAD embedded)
 * translated to JavaScript with binaryen wasm2js (-all -O2), because the game's
 * Cohtml does not expose WebAssembly. Defines one global:
 *
 *     ACEDoomModule(imports) -> exports
 *
 * imports: { console, gameSaving, loading, runtimeControl, ui, env: { getTempRet0 } }
 * exports: memory (.buffer), initGame, tickGame, reportKeyDown, reportKeyUp, KEY_* ({ value })
 */
var %s = (function () {
""" % GLOBAL
FOOTER = """
 return asmFunc;
}());
"""


def find_wasm2js(argv):
    if "--wasm2js" in argv:
        return argv[argv.index("--wasm2js") + 1]
    return os.environ.get("WASM2JS") or shutil.which("wasm2js") or shutil.which("wasm2js.exe")


def convert(es_module):
    """Classic-script text from wasm2js's ES-module output."""
    lines = es_module.splitlines()
    body = [line for line in lines if not re.match(r"^import \* as \w+ from '\w+';$", line)]
    text = "\n".join(body)
    cut = text.find("\nvar retasmFunc = asmFunc({")
    if cut < 0:
        raise SystemExit("wasm2js output: 'var retasmFunc = asmFunc({' not found")
    text = text[:cut]
    if "function asmFunc(imports) {" not in text:
        raise SystemExit("wasm2js output: asmFunc(imports) not found")
    if re.search(r"^(import|export) ", text, re.M):
        raise SystemExit("wasm2js output: an import/export line survived")
    return HEADER + text + FOOTER


def main(argv):
    wasm2js = find_wasm2js(argv)
    if not wasm2js or not os.path.isfile(wasm2js):
        raise SystemExit("wasm2js not found: pass --wasm2js <path> or set WASM2JS (binaryen release)")
    if not os.path.isfile(SOURCE):
        raise SystemExit(f"{SOURCE} missing")
    raw = OUTPUT + ".raw"
    subprocess.run([wasm2js, "-all", "-O2", SOURCE, "-o", raw], check=True)
    try:
        with open(raw, encoding="utf-8") as f:
            text = convert(f.read())
    finally:
        os.remove(raw)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUTPUT} ({os.path.getsize(OUTPUT):,} bytes) from {SOURCE} ({os.path.getsize(SOURCE):,} bytes)")


if __name__ == "__main__":
    main(sys.argv[1:])
